# This is the base configuration for all environments
[base]

# The name of the site
name = "Questify"

# Define redirects

 [[redirects]]
  from = "/*"
  to = "/"
  status = 200 

# Enable TLS/SSL
[ssl]
  enable = true
  redirect = true